INSERT INTO `tasks` (`title`) VALUES ("sample-task-01");
INSERT INTO `tasks` (`title`) VALUES ("sample-task-02");
INSERT INTO `tasks` (`title`) VALUES ("sample-task-03");
INSERT INTO `tasks` (`title`) VALUES ("sample-task-04");
INSERT INTO `tasks` (`title`, `is_done`) VALUES ("sample-task-05", true);
INSERT INTO `ownership` VALUES (0, 1);
INSERT INTO `ownership` VALUES (0, 2);
INSERT INTO `ownership` VALUES (0, 3);
INSERT INTO `ownership` VALUES (0, 4);
INSERT INTO `ownership` VALUES (0, 5);